apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nls-accessibility-map-cache
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azurefile
  resources:
    requests:
      storage: 4Gi
