apiVersion: batch/v1
kind: Job
metadata:
  name: nls-accessibility-map-graphhopper-job-initialise-network-init
  labels:
    tags.datadoghq.com/service: nls-accessibility-map-graphhopper-job-initialise-network-init
    tags.datadoghq.com/env: { { $.Values.environment } }
    tags.datadoghq.com/version: "{{ .Chart.AppVersion }}"
spec:
  ttlSecondsAfterFinished: 604800
  activeDeadlineSeconds: 86400
  backoffLimit: 3
  template:
    metadata:
      annotations:
        ad.datadoghq.com/{{ .Chart.Name }}.logs: '[{"source": "java", "service": "nls-accessibility-map-graphhopper-job-initialise-network-init"}]'
        admission.datadoghq.com/java-lib.version: "{{ .Values.datadog.agent.version }}"
      labels:
        app: nls-accessibility-map-graphhopper-job-initialise-network-init
        environment: { { $.Values.environment } }
        admission.datadoghq.com/enabled: "true"
        tags.datadoghq.com/service: nls-accessibility-map-graphhopper-job-initialise-network-init
        tags.datadoghq.com/env: { { $.Values.environment } }
        tags.datadoghq.com/version: "{{ .Chart.AppVersion }}"
    spec:
      containers:
        - name: nls-accessibility-map-graphhopper-job-network-init
          resources:
            limits:
              memory: 8Gi
            requests:
              memory: 8Gi
          image: ndwnls.azurecr.io/nls-accessibility-map-graphhopper-job:{{ $.Chart.AppVersion }}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: nls-accessibility-map-jobs-config
          env:
            - name: COMMAND
              value: initialiseNetwork
            - name: SPRING_PROFILES_ACTIVE
              value: { { .Values.environment } }
            - name: JAVA_TOOL_OPTIONS
              value: -Xshare:off -XX:MaxRAMPercentage=70 -Ddatadog.slf4j.simpleLogger.logFile=System.out -Ddatadog.slf4j.simpleLogger.dateTimeFormat="yyyy-MM-dd HH:mm:ss.SSS"
          volumeMounts:
            - mountPath: /application/config
              name: nls-accessibility-map-api-secrets
              readOnly: true
            - mountPath: /application/heapdumps
              name: nls-accessibility-map-heapdump
              subPath: nls-accessibility-map-graphhopper-job-network-init
            - mountPath: /application/graphhopper
              name: nls-accessibility-map-graphhopper-job-network-init-volume
      restartPolicy: Never
      volumes:
        - name: nls-accessibility-map-api-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: nls-accessibility-map-jobs-spc
        - name: nls-accessibility-map-heapdump
          persistentVolumeClaim:
            claimName: heapdump-pvc-claim
        - name: nls-accessibility-map-graphhopper-job-network-init-volume
          persistentVolumeClaim:
            claimName: nls-accessibility-map-api-pvc
