jooq:
  schema-validation:
    schema-severity:
      nwb: ERROR
    packages-to-scan:
      - nu.ndw.nls.db.nwb.jooq.generated

org:
  jooq:
    no-logo: true
spring:
  application:
    name: nls-accessibility-map-job
  # Disables netty webserver startup
  main:
    web-application-type: none
  config:
    import: "optional:configtree:/application/config/configtree/"
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: SELECT 1;
      idle-timeout: 60000
      max-lifetime: 120000
      minimum-idle: 1
      auto-commit: false
  security:
    oauth2:
      client:
        registration:
          sa-nls-location-data-issues-api:
            authorization-grant-type: client_credentials
            client-id: ${keycloak.client-id}
            client-secret: ${keycloak.client-secret}
            provider: ndw-keycloak
          traffic-sign-area-backend:
            authorization-grant-type: client_credentials
            client-id: ${keycloak.client-id}
            client-secret: ${keycloak.client-secret}
            provider: ndw-keycloak
        provider:
          ndw-keycloak:
            token-uri: ${keycloak.server-url}/realms/ndw/protocol/openid-connect/token
  jmx:
    enabled: false
  jooq:
    sql-dialect: Postgres

nu:
  ndw:
    nls:
      springboot:
        messaging:
          publish:
            - routingKey: ndw.nls.accessibility.routing.network.updated
              expectedEventType: ACCESSIBILITY_ROUTING_NETWORK_UPDATED
            - routingKey: ndw.nls.maps.accessibility-window-times-rvv-code-c6.geojson.published
              expectedEventType: MAP_GEOJSON_PUBLISHED_EVENT
              eventSubjectType: ACCESSIBILITY_WINDOWS_TIMES_RVV_CODE_C6
            - routingKey: ndw.nls.maps.accessibility-window-times-rvv-code-c7.geojson.published
              expectedEventType: MAP_GEOJSON_PUBLISHED_EVENT
              eventSubjectType: ACCESSIBILITY_WINDOWS_TIMES_RVV_CODE_C7
            - routingKey: ndw.nls.maps.accessibility-window-times-rvv-code-c7b.geojson.published
              expectedEventType: MAP_GEOJSON_PUBLISHED_EVENT
              eventSubjectType: ACCESSIBILITY_WINDOWS_TIMES_RVV_CODE_C7B
            - routingKey: ndw.nls.maps.accessibility-window-times-rvv-code-c12.geojson.published
              expectedEventType: MAP_GEOJSON_PUBLISHED_EVENT
              eventSubjectType: ACCESSIBILITY_WINDOWS_TIMES_RVV_CODE_C12
            - routingKey: ndw.nls.maps.accessibility-window-times-rvv-code-c22c.geojson.published
              expectedEventType: MAP_GEOJSON_PUBLISHED_EVENT
              eventSubjectType: ACCESSIBILITY_WINDOWS_TIMES_RVV_CODE_C22C
          receive:
            - queue: nls_accessibility_map_data_analyser_analyse_base_network
              routingKey: ndw.nls.accessibility.routing.network.updated
              expectedEventTypes:
                - ACCESSIBILITY_ROUTING_NETWORK_UPDATED
            - queue: nls_accessibility_map_graphhopper_job_nwb_imported
              routingKey: ndw.nls.nwb.imported
              expectedEventTypes:
                - NWB_IMPORTED_EVENT
      locationdataissuesapi:
        issue:
          url: ${feign.client.base-url}/rest/static-road-data/location-data-issues/v1
        report:
          url: ${feign.client.base-url}/rest/static-road-data/location-data-issues/v1
        client:
          feign:
            oauth2:
              registration-id: sa-nls-location-data-issues-api
      accessibilitymap:
        jobs:
          generate:
            zone: "Europe/Amsterdam"
            root-export-directory: "/application/maps"
            relative-export-directory-pattern: "'v1/windowTimes/'yyyyMMdd'/geojson/'"
            add-traffic-signs-as-points: true
            add-traffic-signs-as-line-strings: true
            traffic-sign-line-string-distance-in-meters: 1
            add-all-road-section-fragments: false
            add-road-segment-fragments-that-are-blocked-in-all-available-directions: true
            add-road-segment-fragments-that-are-accessible-in-all-available-directions: false
            write-road-segment-fragments-that-are-partially-accessible-as-accessible: true
        trafficsignclient:
          api:
            url: https://data.ndw.nu/api/rest/static-road-data/traffic-signs/v4
        network:
          cache:
            name: "Network"
            folder: "./cache/network"
            load-data-on-startup: false
            watch-for-updates: false
        trafficSigns:
          emission-zone:
            client:
              url: https://wegkenmerken.ndw.nu/api/area/ibbm/emission-zones/v1
              oauth2:
                registration-id: traffic-sign-area-backend
          cache:
            name: "Traffic sign"
            folder: "./cache/trafficSigns"
            load-data-on-startup: false
            watch-for-updates: false

resilience4j.retry:
  instances:
    emissionZone:
      maxAttempts: 3
      waitDuration: 1s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - feign.codec.DecodeException
        - feign.FeignException.InternalServerError
        - feign.RetryableException

management:
  observations:
    annotations:
      enabled: true

logging:
  level:
    root: WARN
    nu.ndw.nls: INFO
    nu.ndw.nls.accessibilitymap.accessibility.services.mappers.TrafficSignSnapMapper: ERROR
    nu.ndw.nls.accessibilitymap.accessibility.graphhopper.querygraph.QueryGraphConfigurer: ERROR
